### PR TITLE
Allow filtering of jobs by input text on list view

### PR DESCRIPTION
**Pull request by steverobbins**
Here's my take on #166.  This adds a configurable option to change the `job_code` filter from a `select` to the default text input.

By default, nothing changes unless you update your config.

### CODE REVIEW

**Comment by LeeSaferite** [comment]
Seems like a decent solution to the request.

@fbrnc ?

**Comment by LeeSaferite** [comment]
If you update this to add a case for `text` and a default case then I'll merge it. The `text` case can fall-through to the default, but I'd like it there so that it's explicit.

**Comment by steverobbins** [comment]
You got it boss.

**Comment by fbrnc** [comment]
Nice solution. Thank you very much, @steverobbins!

**Pull request merged**
