### PR TITLE
Issue/189 force user

### PR DESCRIPTION
**Pull request by robbieaverill**
### Done
* Added configuration options:
 * Which user should run the cron 
 * Whether to warn or kill schedules run as the wrong user
 * Whether to show the warning messages in the admin panel
* Check when running via CLI, log the last user to run a schedule if it successfully starts (ignore if it's the wrong user and setting is set to kill!)
* Added status message "wrong_user"

### Todo

* ~~Unit tests~~
* ~~Squash!~~

### CODE REVIEW

**Comment by robbieaverill** [comment]
Hey @fbrnc 

If you have some time, would you mind doing some QA over this ticket? The logic around messages, hiding or showing and giving CTAs for the user can get a bit complicated.

Do you want the `--force` flag to override the warn/kill setting?

Thanks!
Robbie

**Comment by robbieaverill** [comment]
Woops - took a bunch of code out by accident. Fixing...

**Comment by robbieaverill** [comment]
Will work on some unit tests now and remove the added and empty `@param` as Scrutinizer pointed out :)

**Comment by robbieaverill** [comment]
Tests updated:

* Added unit tests for the new helper methods that have a bit of logic
* Check that jobs are killed when the kill switch is on (and user is wrong)
* Check that jobs are allowed to run if the kill switch is off (and user is wrong)
* Moved model and helper alias resolution unit tests into a separate Config unit test class

Let me know how you get on with the functionality.

**Comment by robbieaverill** [comment]
The tests in `Aoe_Scheduler_Test_Model_Schedule_Scheduling::scheduleJobAndRunCron` are too inconsistent IMO - I think I've mentioned this in another issue #191 - they need to be fixtured or mocked properly so they don't rely on the system or existing data

**Comment by fbrnc** [comment]
Hi @robbieaverill,

I'm just noticing right now that all the notification email were hiding in my GitHub folder. I'm sorry for the massive delay.
I just had a closer look at the code and tested it locally. I did some minor modifications and I'm going to merge it into master in a minute.
Thank you so much for this contribution. It turned out great!

**Comment by fbrnc** [comment]
I do still have an issue running the tests, but that doesn't seem to be related to this PR since all other tests are also failing. So I'll have to look into that...

**Comment by robbieaverill** [comment]
Hey @fbrnc 

Thanks for that. The failing tests seem to be inconsistent, will work sometimes and not others. I've logged another issue to mock the filesystem for those tests that actually run full end to end processes, since they aren't really unit tests.

Cheers!

Robbie

**Pull request merged**
